version: '3'
services:
  drivesensescreen:
    build: .
    container_name: drivesensescreen
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: ["npx", "electron", "."]
